sudo: required

services:
  - docker

script:
  - export TAG_JDK=gmaslowski/jdk:$TRAVIS_COMMIT
  - export TAG_JRE=gmaslowski/jre:$TRAVIS_COMMIT
  - docker run -it --rm -v "$(pwd)/jdk8/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
  - docker run -it --rm -v "$(pwd)/jre8/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
  - docker build ./jdk8 -t $TAG_JDK
  - docker build ./jre8 -t $TAG_JRE

after_success:
  - export JDK_VERSION_MINOR=`cat jdk8/Dockerfile | grep "ENV JAVA_VERSION_MINOR" | awk '{print $3}'`
  - export JRE_VERSION_MINOR=`cat jre8/Dockerfile | grep "ENV JAVA_VERSION_MINOR" | awk '{print $3}'`
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $TAG_JDK gmaslowski/jdk:8 
  - docker tag $TAG_JDK gmaslowski/jdk:8u$JDK_VERSION_MINOR
  - docker tag $TAG_JDK gmaslowski/jdk:latest
  - test $TRAVIS_BRANCH = "master" && docker push gmaslowski/jdk:8
  - test $TRAVIS_BRANCH = "master" && docker push gmaslowski/jdk:8u$JDK_VERSION_MINOR
  - test $TRAVIS_BRANCH = "master" && docker push gmaslowski/jdk:latest
  - docker tag $TAG_JRE gmaslowski/jre:8 
  - docker tag $TAG_JRE gmaslowski/jre:8u$JRE_VERSION_MINOR
  - docker tag $TAG_JRE gmaslowski/jre:latest
  - test $TRAVIS_BRANCH = "master" && docker push gmaslowski/jre:8
  - test $TRAVIS_BRANCH = "master" && docker push gmaslowski/jre:8u$JRE_VERSION_MINOR
  - test $TRAVIS_BRANCH = "master" && docker push gmaslowski/jre:latest
